site_name: Steel Surface Defect Classification
site_description: CNN-based classification of steel surface defects

theme:
  name: material
  palette:
    primary: deep orange
    accent: blue grey
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy

nav:
  - Final Project: index.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
